spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_PATH}/cotato
    username: root
    password: ${DB_PWD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 1800000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 1800000

  refresh:
    expiration: 86400000

cloud:
  aws:
    s3:
      bucket: cotato
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_ACCESS_PASSWORD}

springdoc:
  show-login-endpoint: true
